### PR TITLE
feat: added whatsapp plugin for v6 with multiple business api support

### PR DESCRIPTION
**Pull request by CodeSyncr**
It is the plugin for whatsapp business api integration best suitable for whatsapp based saas like wati

### CODE REVIEW

**Comment by Julien-R44** [comment]
Hey, thanks for the PR!

I'd say it would be best to contact the original maintainer of the package and offer a pull request. Otherwise, we end up with a duplicate on packages.adonisjs.com and that might confuse people. 

What do you think?

**Comment by CodeSyncr** [comment]
> Hey, thanks for the PR!
> 
> I'd say it would be best to contact the original maintainer of the package and offer a pull request. Otherwise, we end up with a duplicate on packages.adonisjs.com and that might confuse people.
> 
> What do you think?

Hey Julien,

Thanks for your response! I completely understand and respect your preference for keeping things simple. I want to highlight that my package takes a different approach and introduces unique features that might cater to a specific use case. It focuses on building wati like functionality where we can get connect to multiple whatsapp number webhooks at same time

**Comment by CodeSyncr** [comment]
> > Hey, thanks for the PR!
> > I'd say it would be best to contact the original maintainer of the package and offer a pull request. Otherwise, we end up with a duplicate on packages.adonisjs.com and that might confuse people.
> > What do you think?
> 
> Hey Julien,
> 
> Thanks for your response! I completely understand and respect your preference for keeping things simple. I want to highlight that my package takes a different approach and introduces unique features that might cater to a specific use case. It focuses on building wati like functionality where we can get connect to multiple whatsapp number webhooks at same time

I tried connecting with original author but he wants to keep things simple, so decided to recreate the package and modify it as per saas platform which will be helpfull when you are integration whatsapp for multiple clients.

**Comment by CodeSyncr** [comment]
> Hey, thanks for the PR!
> 
> 
> 
> I'd say it would be best to contact the original maintainer of the package and offer a pull request. Otherwise, we end up with a duplicate on packages.adonisjs.com and that might confuse people. 
> 
> 
> 
> What do you think?

Hey will you be able to merge it

**Comment by Julien-R44** [comment]
Let's merge it and see how it goes. Because i am still not sure how to handle this problem
Having lot of duplicate packages will lead to something confusing

Thanks!

**Pull request merged**
