### PR TITLE
feat: add adonis6_ally_vk and adonis6_ally_yandex packages

### PR DESCRIPTION
**Pull request by dmitry-makovsky**
Two Ally drivers (yandex, vk.com), compatible with AdonisJS 6

### CODE REVIEW

**Comment by Julien-R44** [comment]
Hey! Thanks for the PR

Two small things:

- It looks like you’re using a pre-release peer dependency for `@adonisjs/core` and `@adonisjs/ally`. Could you please update it?  https://github.com/dmitry-makovsky/adonis6_ally_vk/blob/main/package.json#L27 
- Also, it would be great to add a `configure.ts` file to automatically handle environment variables and their validations. You can find an example here: https://github.com/RomainLanz/ally-twitch/blob/main/configure.ts. This way, when a user runs `node ace add adonis6-ally-vk`, they will automatically get a populated `.env`, `.env.example`, and `env.ts`.

Other than that, it looks good. Thanks!

**Comment by dmitry-makovsky** [comment]
Hi Julien,
Thank you for pointing this out! I’ll address these issues in the next few days.

**Comment by dmitry-makovsky** [comment]
@Julien-R44 

Hi Julien,

I’ve fixed everything, including the package names that were incorrect. Thanks for highlighting how to handle automatic configuration — it works great now!

**Comment by Julien-R44** [comment]
Thanks dude!

**Pull request merged**
