### PR TITLE
fix: 🐛 updated package path

### PR DESCRIPTION
**Pull request by hsharma1996**
Fixed a typo. 
I apologize for the trouble.

### CODE REVIEW

**Comment by hsharma1996** [comment]
@RomainLanz @thetutlage Please merge. Thanks

**Comment by hsharma1996** [comment]
@thetutlage  even the package path is correct. Still is not deployed. can you suggest where I went wrong ?

**Comment by RomainLanz** [comment]
What do you mean?

It works as expected: https://packages.adonisjs.com/packages/advance-redis-rpc

**Comment by thetutlage** [comment]
@RomainLanz The website was broken for a while, but @Julien-R44 fixed it later.

**Pull request merged**
